FROM alpine:latest
LABEL Version="1.0.0"
LABEL Description="Dev Env for Typescript projects."
#Run things as ROOT
RUN apk add --update nodejs npm jq nano tree doas
#RUN adduser --disabled-password --gecos "" -s /bin/ash jarvis -G wheel
#RUN echo "jarvis:jarvis" | chpasswd 
#RUN echo "permit persist :wheel as root" >> /etc/doas.d/doas.conf
#RUN things as jairo
#USER jarvis
WORKDIR /home/app
ENV ENV="/root/.ashinit"
RUN echo -e "\n#Aliases for all Profiles \nalias ll='ls -la'\nalias dev='cd /home/app'" >> ~/.ashinit
