FROM ubuntu:latest
LABEL Version="1.0.0"
LABEL Description="Unofficial Docker image for NJIT Big Data 2022 Fall Grad class with Scala 3 "
ENV HOME_DIR="/home/scala3"
RUN useradd -rm -d /home/scala3 -s /bin/bash/ -g root -G sudo -u 1001 BGstudent
#USER BGstudent
WORKDIR /home/scala3
RUN apt-get update && apt-get upgrade -y && apt-get install curl -y
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install tzdata -y && apt-get install default-jre -y
RUN curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -y